application: belay-belay
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: index.py
  login: required

- url: /manage
  script: index.py
  login: required

- url: /subbelay
  script: index.py
  login: required

- url: /(.*\.(html|css|js))
  static_files: \1
  upload: (.*\.(html|css|js))

- url: /images
  static_dir: images

builtins:
- admin_redirect: on
- datastore_admin: on
- appstats: on

