application: belay-bfriendr
version: 1
runtime: python
api_version: 1

handlers:

- url: /generate
  script: bfriendr.py

- url: /cap/.*
  script: bfriendr.py

- url: /(.*\.(html|css|js|png))
  script: lib/CORSstatic.py
